### ISSUE TITLE
Deprecation alerts with Atom 1.13.0 

### ISSUE THREAD

**Issue by snowbillr** [opattison/newbound-light-syntax#13]
Bunch of deprecation alerts for this theme after upgrading to 1.13.0. Most relevant info seems to be:

> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

Then it lists a bunch of selectors.

> Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

The offending file is `newbound-light-syntax/index.less`

For the record, I love the theme and have been using it for a while now. Thank you!

**Comment by opattison** [comment]
I’m stuck on 1.12 at the moment so I hadn’t seen this yet, but I will post a fix.

Thanks for reporting!

**Comment by opattison** [comment]
@billnreed Deprecation issue is now fixed, but I’ll have to give this a few hours of use before publishing to atom.io. I use this theme every day and want to make sure it’s completely compatible with existing syntaxes.

I will also be updating the sibling dark and warm syntax themes once I get this published.

**Comment by snowbillr** [comment]
Good stuff, thank you!

**Comment by opattison** [comment]
Updated. https://atom.io/themes/newbound-light-syntax

Let me know if you see any issues.
