### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by gristel** [opattison/newbound-light-syntax#6]
Could you please provide a JavaScript screenshot in your README?
Thanks!

**Comment by opattison** [comment]
Yep – will do!

**Comment by opattison** [comment]
I am working on better screenshots in another release (want to make sure everything is stable and consistent first). So here’s a sample in the meantime in JavaScript (with and without invisibles):

![2016-03-27 12 57 08](https://cloud.githubusercontent.com/assets/885300/14066581/96bbf48a-f41b-11e5-8c42-3009df42f62b.png)

![2016-03-27 12 59 07](https://cloud.githubusercontent.com/assets/885300/14066588/c8553010-f41b-11e5-8b0e-f875ad2f5b11.png)

**Comment by opattison** [comment]
Some other working examples (JSON, Markdown, YAML, SCSS):

![2016-03-27 13 04 13](https://cloud.githubusercontent.com/assets/885300/14066640/1df65c50-f41d-11e5-9825-f2c3ddf88b2d.png)

![2016-03-27 13 04 27](https://cloud.githubusercontent.com/assets/885300/14066641/223597ea-f41d-11e5-83f6-814bd428b8c3.png)

![2016-03-27 13 07 09](https://cloud.githubusercontent.com/assets/885300/14066643/27fd1860-f41d-11e5-9bd9-bf35753fa5df.png)

![2016-03-27 13 07 28](https://cloud.githubusercontent.com/assets/885300/14066644/3051fd32-f41d-11e5-9cd8-61e32f13e645.png)

![2016-03-27 13 08 20](https://cloud.githubusercontent.com/assets/885300/14066652/359fe8da-f41d-11e5-9534-f94b1888490e.png)

**Comment by gristel** [comment]
Thanks! And looking good..

**Comment by opattison** [comment]
@gristel Thanks – will be finishing it soon and possibly making some other variants.
